<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../SharedImports/CsProj.Props/AllImportsForRealCode-Eav.props" />

  <!-- Activating docs for this DLL in v22.01 -->
  <Import Project="../SharedImports/CsProj.Props/CreateXDocsOnRelease.props" />

  <ItemGroup>
    <ProjectReference Include="..\ToSic.Eav.Data\ToSic.Eav.Data.csproj" />
  </ItemGroup>

</Project>
