<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../SharedImports/CsProj.Props/AllImportsForTestCode-Sys.props" />

  <PropertyGroup>
    <RootNamespace>ToSic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xunit.Priority" Version="1.1.6" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ToSic.Sys.Core\ToSic.Sys.Core.csproj" />
    <ProjectReference Include="..\ToSic.Sys.TestHelpers\ToSic.Sys.TestHelpers.csproj" />
  </ItemGroup>

</Project>